#!/usr/bin/perl

# Name:          run_all.pl
# Purpose:       test runner - runs a suite of tests and create reports
#                also updates the database with individual
#                test results, serves as the heart of the Tapat program

use strict;
use warnings;
use TAP::Parser qw/all/;
use TAP::Parser::Aggregator qw/all/;
use File::Basename;
use DBI;

chomp(my $time_now = `date +"%Y-%m-%d %X"`);
open (my $report, ">", "/tmp/report") or die "$0 cannot open report. $!\n";
print $report "-= $time_now Automated Test Script =-\n\n";

sub update_case {    # Insert test case data into database
  my $dbh = DBI->connect("DBI:mysql:database=lotc_testing;host=localhost",
                         "root", "rootroot", {'RaiseError' => 1}) or die "Cannot connect: $!\n";
  my ($tc, $result) = @_;
  $dbh->do("UPDATE test_cases
            SET last_run = NOW(), result = '$result'
            WHERE tc_id = '$tc'
            AND cluster_id = '0' ");  ### <- set cluster_id here
  $dbh->disconnect;
}

my ($planned, $total_passed, $total_failed, $total_run);
my @test_cases = qw[
		     
      ];

# Aggregate test results
my $aggregate = TAP::Parser::Aggregator->new;
foreach my $file (@test_cases) {
  my $test = fileparse($file);
  my ($script, $test_id) = split /_/, $test;
  print $report "\tOverview for $test at $time_now\n";

  # New parser for each test file
  my $parser = TAP::Parser->new( { source => $file } );
  $aggregate->start();            # start timer
  $aggregate->add($file, $parser);

  while ( my $result = $parser->next ) {
    # write to the log file
    open (my $log, ">>", "/var/log/test.log" )
      or die "$0 cannot open log file. $!\n";
    my $out = $result->as_string;
    print $log "$out\n";
    if ($result->is_plan) {
      $planned = $result->tests_planned;
    }
  }
  $aggregate->stop();             # stop timer

  my $elapsed = $aggregate->elapsed_timestr();
  my $failed = $parser->failed;
  my $passed = $parser->passed;
  $total_passed += $passed;
  $total_failed += $failed;

  # If we ran all our unit tests, and they all passed
  if ($parser->is_good_plan && ($passed - $failed == $planned)) {
    print $report "\nPassed all our planned tests\nUpdating database for test case: $test_id\n";
    &update_case($test_id, "pass");
    print $report "\nElapsed time: $elapsed\nPassed: $passed\nFailed: $failed\n---\n";
  } else {
    print $report "\nERROR in testing output.\nPlanned: $planned tests.\n";
    &update_case($test_id, "fail");
    print $report "\nElapsed time: $elapsed\nPassed: $passed\nFailed: $failed\n---\n";
  }
}

print $report "\nTotal passed tests: $total_passed\nTotal failed tests: $total_failed\n";
system "cat /home/lotc/report | mail -s \"Automated testing report for $time_now\" jeremiah.foster\@ericsson.com";

# update xml file
system "/usr/lib/cgi-bin/test_cases/merge.pl > /var/www/test.merge.xml";


1;



